### PR TITLE
65 - decouple searchbar from topbar component

### PR DESCRIPTION
**Pull request by stevenhansel**

### CODE REVIEW

**Review by thegreat-vanderlinde — CHANGES_REQUESTED** [review]
looks good, can we include the search bar in the summary page too? as of now the only page where the search bar is missing is the create contract one

**Comment by stevenhansel** [comment]
> looks good, can we include the search bar in the summary page too? as of now the only page where the search bar is missing is the create contract one

I have added the search bar into the summary page also. Other than that, I just checked the create contract page without the search bar, I think there's an offset difference in the content positioning. Do you have any concerns about this?

Screen Shot 2022-10-04 at 21 55 10

**Comment by thegreat-vanderlinde** [comment]
> I have added the search bar into the summary page also. Other than that, I just checked the create contract page without the search bar, I think there's an offset difference in the content positioning. Do you have any concerns about this?

no no, for now the create contract page is just for internal testing. once we'll be ready we'll go live with something polished

**Review by thegreat-vanderlinde — APPROVED** [review]
lgtm

**Pull request merged**
