### PR TITLE
Mui migration

### LINKED ISSUE #263: Replace Evergreen UI with MUI
We should move all codebase from using Evergreen tags & components, entirely to MUI components.

### PR DESCRIPTION
**Pull request by Shikhar15606**
Migrating from evergreen to material ui

closes #263

### CODE REVIEW

**Comment by thegreat-vanderlinde** [comment]
converting this to a draft until @sudoshreyansh and @stevenhansel push their changes

**Comment by thegreat-vanderlinde** [comment]
@Shikhar15606 @stevenhansel @sudoshreyansh is this PR ready for review?

**Comment by sudoshreyansh** [comment]
@thegreat-vanderlinde no, a few components are remaining.

**Comment by sudoshreyansh** [comment]
@thegreat-vanderlinde There seems to be an issue with the contract summary page currently on the `dev` branch.
It fails on the staging server too: https://staging.demo.otc.vyperprotocol.io/contract/summary/7vgDiAkV2ySYy2q247hUAee4bvtzX4ZRzFsPBtAPbWs4

I was able to localize the issue to the `CoinBadge` component relying on `reserveTokenInfo` of the `otcState` which might not be available for all contracts. Maybe we can fix that in a separate PR?

**Comment by thegreat-vanderlinde** [comment]
> Maybe we can fix that in a separate PR?

Yes definitely. It should be already fixed @vantessel here:
https://github.com/vyper-protocol/vyper-otc-ui/blob/bda8549f3f86e68ec7ab23215ef0b3e4766f6666/src/components/molecules/CoinBadge/CoinBadge.tsx#L18-L35

I'll take care of this.

**Review by thegreat-vanderlinde — APPROVED** [review]

**Pull request merged**
