### PR TITLE
perf(index.tsx): improve loading time of home background image

### LINKED ISSUE #128: Fix home background slow fetching
On a hard refreshed (but sometimes also on standard ones) the home background image takes more than 3/4 seconds to appear. Considering the little image size, 64.11KB, we probably have some fetching inefficiency.

Screenshot 2022-10-06 at 10 02 09

Screenshot 2022-10-06 at 10 03 56

### PR DESCRIPTION
**Pull request by Shikhar15606**
prioritize the image for loading using preloading

fix #128

### CODE REVIEW

**Comment by thegreat-vanderlinde** [comment]
@GnosisAssembler can you please provide also you're review?

**Review by GnosisAssembler — CHANGES_REQUESTED** [review]
Using the `priority` attribute is the way to go in Largest Contentful Paint image, in order for Next.js to specially prioritize the first image for loading. 

Other than that i dont think that it really matters, because using the component `Image` from Next.js, should do the trick, since Next.js does all the necessary optimizations needed. 

I think that what it hurts the performance is that, we are using the Home image with the `layout="fill"` attribute, which causes the image to expand to fill the whole page. 

- Maybe i would also change the `quality={100}` to `quality={50}` , since the image is already a blurred gradient and there is no visual difference. 
- And also convert the image format to `webp`, since `webp` images are significantly smaller than `jpg`.

**Review by GnosisAssembler — APPROVED** [review]
LGTM

**Review by thegreat-vanderlinde — APPROVED** [review]
I still have some annoying delay, but for now this can cover. closing

**Pull request merged**
