### PR TITLE
197 - Fix Wallet UI Styling in Homepage

### LINKED ISSUE #197: Wallet UI card not fully visible
Disconnet wallet not visibile

Screenshot 2022-10-17 at 22 52 39

### PR DESCRIPTION
**Pull request by stevenhansel**
Adjust some styling, especially `overflow: hidden` in the `bg_wrapper` that basically clips the wallet dropdown.

Reference: https://stackoverflow.com/questions/1952344/override-overflowhidden-with-z-index

Closes #197

### CODE REVIEW

**Comment by thegreat-vanderlinde** [comment]
@stevenhansel we have some conflicts, can you please fix?

**Comment by stevenhansel** [comment]
> @stevenhansel we have some conflicts, can you please fix?

Actually, I think the problem is already fixed in this commit f9444b71efe3fa5745389f2c7068930fbf03a5a6, I think this pull request can be closed because it won't have any effect otherwise

**Comment by thegreat-vanderlinde** [comment]
> > @stevenhansel we have some conflicts, can you please fix?
> 
> 
> 
> Actually, I think the problem is already fixed in this commit f9444b71efe3fa5745389f2c7068930fbf03a5a6, I think this pull request can be closed because it won't have any effect otherwise

@GnosisAssembler confirm?

**Review by GnosisAssembler — COMMENTED** [review]
Yes we can close this. It is overwritten by PR #224 .

**Pull request closed without merging**
