### PR TITLE
177 - Introduce Storybook

### LINKED ISSUE #177: Introduce Storybook
We need to introduce [Storybook](https://storybook.js.org/) for UI components.
The website will be hosted on a dedicated url and built with netlify

### PR DESCRIPTION
**Pull request by stevenhansel**
Initialize storybook by:
- Installing the storybook itself
- Integrating with Next.js with the help of [storybook-addon-next](https://github.com/RyanClementsHax/storybook-addon-next)
- Adding a scss-postloader file in order to load scss global variables onto the storybook environment
- Creating one story (`<ButtonPill />`) as the base example for the story itself

Let me know if you want me to add the other stories also!

Screen Shot 2022-10-17 at 21 47 45
Screen Shot 2022-10-17 at 21 47 55

Closes #177

### CODE REVIEW

**Review by thegreat-vanderlinde — CHANGES_REQUESTED** [review]
can you please add some docs in readme / Github wiki? Like how to start the storybook server / add new stories

**Comment by stevenhansel** [comment]
> can you please add some docs in readme / Github wiki? Like how to start the storybook server / add new stories

I have added the documentation for the storybook commands and also a little bit guidelines on how to create/modify stories. Please kindly re-check it, thanks!

**Review by thegreat-vanderlinde — APPROVED** [review]
lgtm

**Comment by thegreat-vanderlinde** [comment]
@GnosisAssembler can you please provide your review?

**Review by GnosisAssembler — APPROVED** [review]
LGTM

**Review by thegreat-vanderlinde — APPROVED** [review]
super

**Pull request merged**
